spring:
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: Prasanna@5030
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.security: TRACE
